export type Lessons = {
  Examples: undefined;
  ClockValuesAndIdentities: undefined;
  Transitions: undefined;
  useTransition: undefined;
  DarkMode: undefined;
  Timing: undefined;
  PanGesture: undefined;
  Spring: undefined;
  Swipe: undefined;
  DynamicSpring: undefined;
  DragToSort: undefined;
  Svg: undefined;
  Trigonometry: undefined;
  Decay: undefined;
  CircularSlider: undefined;
  BezierCurves: undefined;
  PathMorphing: undefined;
  PinchGesture: undefined;
};
